# Generated by Django 4.2.3 on 2023-07-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "PENDING"),
                    (2, "CONFIRMED"),
                    (3, "SENDING"),
                    (4, "DELIVERED"),
                    (5, "CANCEL"),
                ],
                default=1,
            ),
        ),
    ]
