# Generated by Django 4.2.3 on 2023-07-22 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_remove_address_country"),
        ("orders", "0003_transaction_order_city_order_country_order_detail_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="country",
        ),
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
        migrations.AddField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="orders",
                to="accounts.customer",
            ),
        ),
    ]
