# Generated by Django 4.2.3 on 2023-08-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_alter_order_final_price_alter_order_total_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("title", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=False)),
                ("coupon_code", models.IntegerField()),
                ("quantity", models.PositiveIntegerField()),
                ("percent", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name_plural": "coupons",
            },
        ),
    ]
