# Generated by Django 4.2.3 on 2023-08-06 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_coupon"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="detail",
            new_name="address_detail",
        ),
    ]
