# Generated by Django 4.2.3 on 2023-08-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_rename_detail_order_address_detail"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "PENDING"),
                    (2, "CONFIRMED"),
                    (3, "PAYMENT_FAILED"),
                    (4, "SENDING"),
                    (5, "DELIVERED"),
                    (6, "CANCEL"),
                ],
                default=1,
            ),
        ),
        migrations.DeleteModel(
            name="Transaction",
        ),
    ]
