# Generated by Django 4.2.3 on 2023-08-08 07:00

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_order_transaction_id_alter_order_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="coupon",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order",
                to="orders.coupon",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("2"), max_digits=4
            ),
        ),
    ]
