# Generated by Django 4.2.3 on 2023-08-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0012_alter_order_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coupon",
            name="quantity",
        ),
        migrations.AlterField(
            model_name="coupon",
            name="coupon_code",
            field=models.IntegerField(unique=True),
        ),
    ]
