# Generated by Django 4.2.3 on 2023-07-22 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_remove_product_image_productimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="products.discount",
            ),
        ),
    ]
