# Generated by Django 4.2.3 on 2023-07-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_remove_address_country"),
        ("products", "0007_remove_comment_user_comment_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="wish_list",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="wish_list", to="accounts.customer"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                default="images/category_default.png", upload_to="images/"
            ),
        ),
    ]
