# Generated by Django 4.2.3 on 2023-07-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_remove_address_country"),
        ("products", "0008_product_wish_list_alter_category_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="wish_list",
            field=models.ManyToManyField(
                blank=True, related_name="wish_list", to="accounts.customer"
            ),
        ),
    ]
