# Generated by Django 4.2.3 on 2023-07-27 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0009_alter_product_wish_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="wish_list",
            field=models.ManyToManyField(
                blank=True, related_name="wish_list", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
