# Generated by Django 4.2.3 on 2023-07-30 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_alter_comment_customer_alter_product_wish_list"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productimage",
            options={"verbose_name_plural": "Product Images"},
        ),
    ]
