# Generated by Django 4.2.3 on 2023-07-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.IntegerField(choices=[(1, "MALE"), (2, "FEMALE")], default=1),
        ),
    ]
