# Generated by Django 4.2.3 on 2023-07-18 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_address_is_deleted_profile_is_deleted_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name_plural": "Addresses"},
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name_plural": "Profiles"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name_plural": "Users"},
        ),
    ]
