# Generated by Django 4.2.3 on 2023-07-18 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_address_options_alter_profile_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OtpCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=14,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="invalid phone number",
                                regex="^(\\+?|0*)(98)?9[\\d-]{9,}$",
                            )
                        ],
                    ),
                ),
                ("code", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "OTP Codes",
            },
        ),
    ]
