# Generated by Django 4.2.3 on 2023-07-22 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_customerprofile_customer_user_national_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="country",
        ),
    ]
