# Generated by Django 4.2.3 on 2023-08-02 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_user_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customerprofile",
            old_name="Shaba_number",
            new_name="shaba_number",
        ),
        migrations.AlterField(
            model_name="address",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
