# Generated by Django 4.2.3 on 2023-08-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_rename_shaba_number_customerprofile_shaba_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="national_code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
