# Generated by Django 4.2.3 on 2023-08-26 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='shaba_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
