# Generated by Django 4.2.3 on 2023-08-29 21:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_alter_customerprofile_shaba_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerprofile",
            name="shaba_number",
            field=models.CharField(
                blank=True,
                max_length=16,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="invalid shaba number", regex="^[\\d]+$"
                    )
                ],
            ),
        ),
    ]
