# Generated by Django 4.2.3 on 2023-07-27 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_remove_cart_customer_cart_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="user",
            new_name="customer",
        ),
    ]
