# Generated by Django 4.2.3 on 2023-08-08 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_order_coupon_order_shipping"),
        ("cart", "0007_alter_cartitem_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="coupon",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cart",
                to="orders.coupon",
            ),
        ),
    ]
